# Generated by Django 5.0.3 on 2024-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('middlename', models.CharField(max_length=60)),
                ('telephon_number', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
    ]
